import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#8fceff',
    paddingHorizontal: 16,
    paddingTop: 24,
  },
  headerBox: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    marginBottom: 18,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  headerTopBar: {
    height: 54,
    backgroundColor: '#7ec7f9',
  },
  headerContent: {
    alignItems: 'center',
    paddingVertical: 22,
    paddingHorizontal: 16,
    backgroundColor: '#ffffff',
  },
  iconBox: {
    width: 90,
    height: 90,
    borderRadius: 22,
    backgroundColor: '#eef8ff',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  iconEmoji: {
    fontSize: 42,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#2f7fbf',
    textAlign: 'center',
  },
  headerSubtitle: {
    fontSize: 16,
    color: '#3f546e',
    textAlign: 'center',
    marginTop: 8,
  },
  formBox: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    padding: 20,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  label: {
    fontSize: 16,
    color: '#14213d',
    marginBottom: 12,
    marginTop: 12,
    textAlign: 'center',
  },
  input: {
    height: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#cfdcee',
    paddingHorizontal: 16,
    fontSize: 16,
    color: '#1b1f30',
    marginBottom: 16,
    backgroundColor: '#ffffff',
  },
  picker: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#cfdcee',
    backgroundColor: '#ffffff',
    marginBottom: 22,
  },
  button: {
    height: 52,
    borderRadius: 14,
    backgroundColor: '#4caf50',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 6,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  resultText: {
    fontSize: 16,
    color: '#14213d',
    marginTop: 18,
    lineHeight: 22,
    textAlign: 'center',
  },
});
